// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxAB8uiAQOC1d96a2BSbAS1v2UIzlbrxY',
    appId: '1:812254830219:web:9768a4ea348b1286da3e8e',
    messagingSenderId: '812254830219',
    projectId: 'seouldata-b07b4',
    authDomain: 'seouldata-b07b4.firebaseapp.com',
    storageBucket: 'seouldata-b07b4.appspot.com',
    measurementId: 'G-16P870KCSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHPMVG5RyEpMXLXivqfQJ1DpSiXimT0Ss',
    appId: '1:812254830219:android:196918f1919ea0b4da3e8e',
    messagingSenderId: '812254830219',
    projectId: 'seouldata-b07b4',
    storageBucket: 'seouldata-b07b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaR-1EyGc_XNDjEhCP5PGiWCIuIJZau8A',
    appId: '1:812254830219:ios:119f414dcd75dd87da3e8e',
    messagingSenderId: '812254830219',
    projectId: 'seouldata-b07b4',
    storageBucket: 'seouldata-b07b4.appspot.com',
    iosBundleId: 'com.example.seouldata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaR-1EyGc_XNDjEhCP5PGiWCIuIJZau8A',
    appId: '1:812254830219:ios:7fde704ca726099ada3e8e',
    messagingSenderId: '812254830219',
    projectId: 'seouldata-b07b4',
    storageBucket: 'seouldata-b07b4.appspot.com',
    iosBundleId: 'com.example.seouldata.RunnerTests',
  );
}
